import { z } from "zod";

// ── Fork ─────────────────────────────────────────────────────────────────────
// A Fork is a decision point the model identified during deliberation.
// Every raised question AND every auto-applied decision starts as a Fork.

export const ForkSchema = z.object({
  /** Stable identifier generated by the deliberation pass. Format: "fork-{situation_id}-{index}" */
  id: z.string(),

  /** Short label for the decision dimension. Examples: "Tone of reminder", "Scope of follow-up memo", "Recipient CC list" */
  dimension: z.string().min(3).max(80),

  /** Full question text shown to the operator if this fork is raised. 1-3 sentences. */
  question: z.string().min(10),

  /** 2-3 proposed options. Each has a label and an explanatory hint. */
  options: z.array(z.object({
    label: z.string().min(2).max(120),
    hint: z.string().min(10).max(300),
  })).min(2).max(3),

  /** Step orders this fork affects. Used to determine which steps enter awaiting_clarification state. */
  affectedStepOrders: z.array(z.number().int().positive()).min(1),

  /** Scope at which a learned preference might exist for this fork. */
  preferenceScope: z.object({
    type: z.enum(["person", "situation_type"]),
    /** Page slug — either the recipient's communication_pattern page or the situation_type_playbook page */
    scopeSlug: z.string(),
  }),

  /** Why this qualifies as a fork (2+ defensible paths, material impact). Used for logging, not shown to operator. */
  materialityRationale: z.string().min(20),
});

export type Fork = z.infer<typeof ForkSchema>;

// ── Open Question ────────────────────────────────────────────────────────────
// A Fork becomes an OpenQuestion when no learned preference clears the threshold.

export const OpenQuestionSchema = ForkSchema.extend({
  /** When the question was raised. ISO-8601 timestamp. */
  raisedAt: z.string(),

  /** If an earlier situation with the same (scopeSlug, dimension) had a custom-text answer, surface it as a pre-fill. */
  priorCustomAnswer: z.string().nullable().optional(),
});

export type OpenQuestion = z.infer<typeof OpenQuestionSchema>;

// ── Auto-Applied Decision ────────────────────────────────────────────────────
// A Fork becomes an AutoAppliedDecision when a learned preference clears the threshold.

export const AutoAppliedDecisionSchema = z.object({
  id: z.string(),
  dimension: z.string(),
  /** The choice auto-applied. Matches one of the option labels from the originating Fork, OR a prior custom answer. */
  choice: z.string(),
  /** Human-readable explanation of why this was auto-applied. Rendered in the Decisions section. */
  basis: z.string().min(10),
  affectedStepOrders: z.array(z.number().int().positive()).min(1),
  preferenceScope: z.object({
    type: z.enum(["person", "situation_type"]),
    scopeSlug: z.string(),
  }),
  /** Reference to the preference that drove this auto-application, for override attribution. */
  preferenceId: z.string(),
  /** Confidence of the learned preference at the moment of application. 0-1. */
  confidenceAtApplication: z.number().min(0).max(1),
  appliedAt: z.string(),
});

export type AutoAppliedDecision = z.infer<typeof AutoAppliedDecisionSchema>;

// ── Answered Decision ────────────────────────────────────────────────────────
// An OpenQuestion becomes an AnsweredDecision when the operator answers it.

export const AnsweredDecisionSchema = z.object({
  id: z.string(),
  dimension: z.string(),
  question: z.string(),
  /** Raised timestamp from the original OpenQuestion */
  raisedAt: z.string(),
  /** Answered timestamp */
  answeredAt: z.string(),
  /** User ID (from session) who answered. Recorded for audit. */
  answeredByUserId: z.string(),
  /** Page slug of the user who answered (for rendering a person link) */
  answeredBySlug: z.string().nullable(),
  /** Either one of the offered option labels, or a free-text answer. */
  choice: z.string().min(1),
  /** True if the operator wrote a custom answer rather than picking an option. */
  isCustomAnswer: z.boolean(),
  affectedStepOrders: z.array(z.number().int().positive()).min(1),
  preferenceScope: z.object({
    type: z.enum(["person", "situation_type"]),
    scopeSlug: z.string(),
  }),
});

export type AnsweredDecision = z.infer<typeof AnsweredDecisionSchema>;

// ── Discriminated union for rendering ───────────────────────────────────────

export const DecisionSchema = z.discriminatedUnion("kind", [
  AnsweredDecisionSchema.extend({ kind: z.literal("answered") }),
  AutoAppliedDecisionSchema.extend({ kind: z.literal("auto_applied") }),
]);

export type Decision = z.infer<typeof DecisionSchema>;

// ── Learned Preference ───────────────────────────────────────────────────────
// Stored inside ## Learned Preferences markdown sections on wiki pages.

export const LearnedPreferenceSchema = z.object({
  id: z.string(),
  dimension: z.string(),
  scope: z.object({
    type: z.enum(["person", "situation_type"]),
    scopeSlug: z.string(),
  }),
  /** The current majority choice. */
  preferredChoice: z.string(),
  /** EMA-based confidence. 0-1. */
  confidence: z.number().min(0).max(1),
  /** Recency-weighted sample count (decisions decay with age). */
  recencyWeightedSample: z.number().min(0),
  /** Most recent decision timestamp, for recency checks. */
  lastUpdatedAt: z.string(),
  /** For surfacing prior custom answers: a list of distinct custom texts seen, newest first, max 5. */
  priorCustomAnswers: z.array(z.string()).max(5),
  /** Underlying decision history — array of {choice, timestamp, isCustomAnswer}. Newest first. Max 50 entries. */
  history: z.array(z.object({
    choice: z.string(),
    timestamp: z.string(),
    isCustomAnswer: z.boolean(),
  })).max(50),
});

export type LearnedPreference = z.infer<typeof LearnedPreferenceSchema>;

// ── Deliberation Pass Output ─────────────────────────────────────────────────
// The structured output of runDeliberationPass() — consumed by Prompt 2's
// orchestrator. Prompt 2 writes the actual wiki sections from this.

export const DeliberationPassOutputSchema = z.object({
  situationSlug: z.string(),
  completedAt: z.string(),
  openQuestions: z.array(OpenQuestionSchema),
  autoAppliedDecisions: z.array(AutoAppliedDecisionSchema),
  /** Step orders that now have awaiting_clarification status, because they depend on an open question. */
  awaitingStepOrders: z.array(z.number().int().positive()),
  /** Step orders whose drafted content was refined during this pass. */
  refinedStepOrders: z.array(z.number().int().positive()),
  /** Total API cost in cents for the full deliberation pass. */
  apiCostCents: z.number().int().nonnegative(),
  /** Duration in ms of the full pass. */
  durationMs: z.number().int().nonnegative(),
});

export type DeliberationPassOutput = z.infer<typeof DeliberationPassOutputSchema>;
