// ── Meridian Teknik A/S — Story Content ─────────────────────────────────
// ~120 hand-written content items covering 12 story threads.
// ~70% Danish, ~20% English, ~10% German. Manufacturing vocabulary.
// Microsoft 365 connector providers throughout.

import type { SyntheticContent } from "../../synthetic-types";

function daysAgoDate(d: number): string {
  return new Date(Date.now() - d * 86400000).toISOString();
}

export const MERIDIAN_STORIES: SyntheticContent[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // Thread 1 — Müller relationship deterioration (6-month arc, ~15 items)
  // ═══════════════════════════════════════════════════════════════════════

  // 6 months ago: warm, collaborative, "Du" form
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 175, content: "Lieber Jørgen, vielen Dank für die schnelle Lieferung der Sonderbauteile. Die Qualität war wie immer ausgezeichnet. Wir freuen uns auf die weitere Zusammenarbeit und werden die nächste Bestellung voraussichtlich Anfang Februar aufgeben. Mit freundlichen Grüßen, Hans Weber, Müller Maschinenbau GmbH", metadata: { from: "h.weber@mueller-maschinenbau.de", to: "jorgen@meridian-teknik.dk", subject: "Danke für die Lieferung — Batch 2024-Q4-312", direction: "received", date: daysAgoDate(175) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 160, content: "Hej Hans, tak for ordren — vi går i produktion med det samme. Leveringstid 3 uger som aftalt. God jul til dig og familien! Vh Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "h.weber@mueller-maschinenbau.de", subject: "RE: Neue Bestellung — Februar 2026", date: daysAgoDate(160) } },

  // 4 months ago: still friendly but small complaint
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 115, content: "Lieber Jørgen, die letzte Lieferung (Batch 2025-Q1-389) war 3 Tage verspätet. Das ist kein großes Problem, aber bitte beachte das für zukünftige Bestellungen. Unsere Produktionsplanung ist darauf angewiesen, dass die Liefertermine eingehalten werden. Sonst alles bestens — die Qualität stimmt. Gruß, Hans", metadata: { from: "h.weber@mueller-maschinenbau.de", to: "jorgen@meridian-teknik.dk", subject: "Lieferverzögerung — bitte beachten", direction: "received", date: daysAgoDate(115) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 112, content: "Hej Hans, du har helt ret — beklager forsinkelsen. Vi havde et maskinnedbrud der påvirkede tidsplanen. Det burde ikke ske igen. Jeg har bedt Morten om at prioritere jeres ordrer. Vh Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "h.weber@mueller-maschinenbau.de", subject: "RE: Lieferverzögerung — bitte beachten", date: daysAgoDate(112) } },

  // 3 months ago: contact changes to Dr. Schneider, formal "Sie" form
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 85, content: "Sehr geehrter Herr Lund, mein Name ist Dr. Markus Schneider. Ich habe die Verantwortung für den Einkauf von Herrn Weber übernommen, der das Unternehmen verlassen hat. Ich möchte mich kurz vorstellen und einen Termin für ein Kennenlerngespräch vereinbaren. Bitte lassen Sie mich wissen, wann es Ihnen passt. Mit freundlichen Grüßen, Dr. Markus Schneider, Leiter Beschaffung, Müller Maschinenbau GmbH", metadata: { from: "m.schneider@mueller-maschinenbau.de", to: "jorgen@meridian-teknik.dk", subject: "Vorstellung — neuer Ansprechpartner Einkauf", direction: "received", date: daysAgoDate(85) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 82, content: "Sehr geehrter Dr. Schneider, vielen Dank für Ihre Nachricht. Es tut mir leid zu hören, dass Hans das Unternehmen verlassen hat — er war ein geschätzter Partner. Ich würde mich sehr freuen, Sie kennenzulernen. Passt Ihnen nächste Woche Dienstag um 10 Uhr? Mit freundlichen Grüßen, Jørgen Lund, CEO, Meridian Teknik A/S", metadata: { from: "jorgen@meridian-teknik.dk", to: "m.schneider@mueller-maschinenbau.de", subject: "RE: Vorstellung — neuer Ansprechpartner Einkauf", date: daysAgoDate(82) } },

  // 2 months ago: quality complaint, switches to English — distancing signal
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 55, content: "Dear Mr. Lund, we have received batch 2024-Q1-447 and found tolerance issues on 12 of 50 components. The specified tolerance is ±0.05mm but measured values show deviations of up to ±0.12mm on the critical bore diameter. Please provide your corrective action plan within 5 business days. We have placed the entire batch on hold pending your response. Regards, Dr. Markus Schneider, Head of Procurement, Müller Maschinenbau GmbH", metadata: { from: "m.schneider@mueller-maschinenbau.de", to: "jorgen@meridian-teknik.dk", cc: "katja@meridian-teknik.dk", subject: "Quality Issue — Batch 2024-Q1-447 — Tolerance Deviation", direction: "received", date: daysAgoDate(55) } },

  // 1 month ago: formal and terse, no order
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 28, content: "Dear Mr. Lund, thank you for the corrective action report. We note that the root cause analysis attributes the issue to tooling wear. We expect a more robust process control going forward. We are currently reviewing our supplier portfolio and will revert with our assessment in due course. Regards, Dr. M. Schneider", metadata: { from: "m.schneider@mueller-maschinenbau.de", to: "jorgen@meridian-teknik.dk", subject: "RE: Corrective Action Report — Batch 447", direction: "received", date: daysAgoDate(28) } },

  // Most recent: silence — Katja's follow-up unanswered
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 8, content: "Dear Dr. Schneider, I hope this message finds you well. I wanted to follow up on our corrective actions regarding batch 447 and confirm that we have implemented new CMM inspection at every 10th component. We would welcome the opportunity to discuss your upcoming requirements. Please let me know if you would like to schedule a call. Best regards, Katja Nissen, Key Account Manager, Meridian Teknik A/S", metadata: { from: "katja@meridian-teknik.dk", to: "m.schneider@mueller-maschinenbau.de", subject: "Follow-up — Meridian Teknik quality improvements", date: daysAgoDate(8) } },

  // Katja → Torben: internal escalation
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 5, content: "Torben, Dr. Schneider har ikke svaret på min opfølgning og de har ikke bestilt i 6 uger — normalt bestiller de hver 3.-4. uge. Jeg er bekymret for at vi er ved at miste dem. Tonen har ændret sig markant siden Hans Weber gik — alt er formelt og på engelsk nu. Katja", metadata: { from: "katja@meridian-teknik.dk", to: "torben@meridian-teknik.dk", subject: "Müller Maschinenbau — ingen ordre i 6 uger", date: daysAgoDate(5) } },

  // Torben → Jørgen: escalation
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 4, content: "Jørgen, vi er ved at miste Müller. De har ikke bestilt i 6 uger og svarer ikke på Katjas mails. Det er batch 447-sagen der hænger os. Müller var 450K DKK i omsætning sidste år. Kan du ringe til Schneider? Det kræver nok CEO-til-CEO kontakt. Torben", metadata: { from: "torben@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "Müller — risiko for tab af kunde", date: daysAgoDate(4) } },

  // Teams: Katja venting
  { sourceType: "slack_message", connectorProvider: "microsoft-365-teams", daysAgo: 5, content: "Müller har ghostet os. 6 uger uden ordre. Schneider er en helt anden type end Hans — kold og formel. Batch 447-sagen ødelagde tilliden og vi har ikke fået den genoprettet. Vi skal handle nu.", metadata: { channel: "salg", authorEmail: "katja@meridian-teknik.dk", authorName: "Katja Nissen" } },

  // Jørgen internal memo
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 3, content: "Til Katja og Torben — jeg ringer til Dr. Schneider i morgen. Forbered venligst en oversigt over vores leveringshistorik til Müller de seneste 12 måneder, inkl. kvalitetsdata og leveringstider. Vi skal vise at batch 447 var en enkeltstående hændelse. Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "katja@meridian-teknik.dk", cc: "torben@meridian-teknik.dk", subject: "Müller — forberedelse til opkald", date: daysAgoDate(3) } },

  // Katja's data summary
  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 3, content: "Müller Maschinenbau — Leveringshistorik 12 måneder. Total omsætning: 452.000 DKK. Antal ordrer: 14. Gennemsnitlig ordrestørrelse: 32.300 DKK. Leveringspræcision: 92% (11/12 til tiden). Kvalitetsklager: 1 (batch 447, 12/50 enheder). Kontakthistorik: Hans Weber til dec. 2025, Dr. Schneider fra jan. 2026. Seneste ordre: 8. februar 2026 (6 uger uden bestilling). Risikovurdering: HØJ — kunden evaluerer sandsynligvis alternative leverandører.", metadata: { fileName: "Mueller_Leveringshistorik_12mdr.xlsx", author: "Katja Nissen", lastModified: daysAgoDate(3) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 2 — Danfoss contract renewal + expansion (~10 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 14, content: "Kære René, som opfølgning på vores kvartalsmøde vil vi gerne drøfte udvidelse af vores rammeaftale til at omfatte 3 nye produktkategorier: hydraulikkomponenter (Ø25-Ø80mm), specialbolte i rustfrit stål, og CNC-fræsede manifolds. Kan du sende specifikationer og prisindikationer? Rammeaftalen udløber om 90 dage og vi vil gerne have det hele på plads ved fornyelsen. Vh Charlotte Riis, Danfoss", metadata: { from: "charlotte.riis@danfoss.com", to: "rene@meridian-teknik.dk", subject: "Udvidelse af rammeaftale — 3 nye kategorier", direction: "received", date: daysAgoDate(14) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 12, content: "Henrik, Danfoss vil have 3 nye produktkategorier i rammeaftalen — hydraulikkomponenter, specialbolte og CNC-manifolds. Kan du lave specifikationer og kapacitetsvurdering? Vi skal have det klar inden udgangen af april. René", metadata: { from: "rene@meridian-teknik.dk", to: "henrik.b@meridian-teknik.dk", subject: "Danfoss nye kategorier — specifikationer", date: daysAgoDate(12) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 11, content: "René, jeg har ikke kapacitet før maj. Jeg sidder med CNC-opsætning til Grundfos og har 3 udestående CAD-konverteringer i kø. Manifold-specifikationen kræver mindst 2 ugers arbejde alene. Kan Lasse tage noget af det? Henrik", metadata: { from: "henrik.b@meridian-teknik.dk", to: "rene@meridian-teknik.dk", subject: "RE: Danfoss nye kategorier — kapacitet", date: daysAgoDate(11) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 10, content: "Torben, vi har et problem. Danfoss vil have specifikationer til 3 nye kategorier inden april men Henrik har ikke kapacitet. Danfoss er 15% af vores omsætning — vi kan ikke tabe den fornyelse. Kan vi prioritere det? René", metadata: { from: "rene@meridian-teknik.dk", to: "torben@meridian-teknik.dk", subject: "Danfoss — kapacitetsproblem i Engineering", date: daysAgoDate(10) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 9, content: "Morten, Danfoss vil have prøvekørsel på 3 nye produktkategorier. Det er kritisk — 6,3M DKK rammeaftale. Produktion skal prioritere Danfoss-prøvekørsel i uge 15-16. Torben", metadata: { from: "torben@meridian-teknik.dk", to: "morten@meridian-teknik.dk", subject: "Danfoss prøvekørsel — prioritering", date: daysAgoDate(9) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 8, content: "Torben, vi kører allerede på 94% kapacitet. Hvis jeg skal prioritere Danfoss-prøvekørsel skal noget andet rykkes — enten Grundfos-ordren eller NorthPower-leverancen. Hvem skal vente? Morten", metadata: { from: "morten@meridian-teknik.dk", to: "torben@meridian-teknik.dk", subject: "RE: Danfoss prøvekørsel — 94% kapacitet", date: daysAgoDate(8) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 7, content: "Danfoss Framework Agreement — Draft Terms (Confidential). Parterne: Meridian Teknik A/S og Danfoss A/S. Aftaletype: Rammeaftale for levering af præcisionskomponenter. Løbetid: 24 måneder fra underskrift. Estimeret årlig omsætning: 6.300.000 DKK. Nye kategorier (2026): Hydraulikkomponenter Ø25-Ø80mm, Specialbolte rustfrit stål (A4-80), CNC-fræsede manifolds. Leveringsbetingelser: Netto 30 dage, FCA Meridian Teknik. Kvalitetskrav: ISO 9001, 100% CMM-inspektion på kritiske mål. Prisregulering: Årlig indeksregulering baseret på stålprisindeks. Status: UDKAST — afventer specifikationer.", metadata: { fileName: "Danfoss_Rammeaftale_2026_UDKAST.docx", author: "René Vestergaard", lastModified: daysAgoDate(7) } },

  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 6, content: "Kvartalsvis forretningsgennemgang — Danfoss. Deltagere: René og Charlotte Riis (Danfoss). Gennemgang af leveringsperformance, kvalitetsdata og fornyelsesvilkår. Charlotte: Positiv omkring fornyelse men kræver specifikationer inden april. René lover foreløbige tal inden 2 uger.", metadata: { title: "QBR — Danfoss", attendees: ["rene@meridian-teknik.dk", "charlotte.riis@danfoss.com"], date: daysAgoDate(6) } },

  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 5, content: "Danfoss — rammeaftale status. Jørgen, Torben, René. Danfoss er vores vigtigste kunde (15% omsætning). Fornyelse kræver specifikationer inden april. Henrik er overbelastet. Beslutning: Lasse hjælper Henrik med hydraulikspecifikation. Morten prioriterer Danfoss-prøvekørsel over NorthPower (NorthPower informeres om 1 uges forsinkelse).", metadata: { title: "Danfoss rammeaftale — intern strategi", attendees: ["jorgen@meridian-teknik.dk", "torben@meridian-teknik.dk", "rene@meridian-teknik.dk"], date: daysAgoDate(5) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 4, content: "Charlotte, tak for mødet i fredags. Vi arbejder på specifikationer til de 3 nye kategorier og sender foreløbige tal inden 2 uger. Vedr. priser — vi har noteret jeres ønske om volumindeksering. Lad mig vende tilbage med et konkret forslag. Vh René Vestergaard, Meridian Teknik", metadata: { from: "rene@meridian-teknik.dk", to: "charlotte.riis@danfoss.com", subject: "RE: QBR opfølgning — specifikationer og priser", date: daysAgoDate(4) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 3 — StålGruppen bidirectional mess (~12 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 20, content: "Til Meridian Teknik A/S, att. Birgitte Holm. Vi bemærker at faktura SG-2026-0112 på 89.000 DKK for levering af specialstål (S355J2+N) stadig er ubetalt efter 28 dage. Betalingsbetingelserne er netto 30 dage. Vi beder venligst om betaling inden 5 hverdage. Flemming Stål, StålGruppen A/S", metadata: { from: "flemming@staalgruppen.dk", to: "birgitte@meridian-teknik.dk", subject: "Betalingspåmindelse — SG-2026-0112", direction: "received", date: daysAgoDate(20) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 15, content: "Kære Meridian Teknik, dette er en 2. rykker vedr. faktura SG-2026-0112 (89.000 DKK). Fakturaen er nu 33 dage gammel. Vi gør opmærksom på at vi tilbageholder betaling af jeres faktura MT-2026-0404 (145.000 DKK) for overskudsstålet indtil vores mellemværende er afklaret. Flemming Stål, StålGruppen A/S", metadata: { from: "flemming@staalgruppen.dk", to: "birgitte@meridian-teknik.dk", subject: "2. rykker — SG-2026-0112 + tilbageholdelse af betaling", direction: "received", date: daysAgoDate(15) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 14, content: "Jørgen, StålGruppen-situationen er ved at eskalere. De skylder os 145.000 DKK (MT-2026-0404) og tilbageholder betalingen som gidsel fordi vi skylder dem 89.000 DKK (SG-2026-0112). Netto skylder de os 56.000 DKK men de nægter at betale noget som helst. Vi har brug for en løsning — enten betaler vi dem og kræver vores penge, eller vi foreslår modregning. Birgitte", metadata: { from: "birgitte@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "StålGruppen — dobbeltrolle skaber problemer", date: daysAgoDate(14) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 13, content: "Birgitte, lav et afregningsforslag — modregning af de 89K mod deres 145K, så de betaler os differencen på 56K. Send det til Flemming og CC mig. Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "birgitte@meridian-teknik.dk", subject: "RE: StålGruppen — modregning", date: daysAgoDate(13) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 12, content: "Flemming, som drøftet foreslår vi følgende afregning: Meridian Teknik skylder StålGruppen: 89.000 DKK (SG-2026-0112). StålGruppen skylder Meridian Teknik: 145.000 DKK (MT-2026-0404). Modregning: 89.000 DKK. Restbeløb til Meridian Teknik: 56.000 DKK. Vi foreslår at modregningen effektueres pr. 1. april og restbeløbet betales inden 14 dage. Venlig hilsen, Tina Gram, Regnskab, Meridian Teknik A/S", metadata: { from: "tina@meridian-teknik.dk", to: "flemming@staalgruppen.dk", cc: "birgitte@meridian-teknik.dk", subject: "StålGruppen / Meridian Teknik — afregningsforslag", date: daysAgoDate(12) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 10, content: "Tina, vi har modtaget jeres afregningsforslag. Vi accepterer princippet men bestrider beløbet på MT-2026-0404 — vi mener prisen på overskudsstålet var aftalt til 130.000 DKK, ikke 145.000 DKK. Kan I sende den originale ordrebekræftelse? Flemming", metadata: { from: "flemming@staalgruppen.dk", to: "tina@meridian-teknik.dk", subject: "RE: Afregningsforslag — prisafvigelse", direction: "received", date: daysAgoDate(10) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 9, content: "StålGruppen A/S — Afregningsforslag. Dato: marts 2026. Baggrund: StålGruppen er both leverandør og kunde hos Meridian Teknik. Leverandørforhold: StålGruppen leverer specialstål (S355J2+N, AISI 316L) til Meridian Teknik. Kundeforhold: Meridian Teknik sælger overskudsstål og restmateriale til StålGruppen. Nuværende udeståender: MT skylder SG: 89.000 DKK (forfald overskredet). SG skylder MT: 145.000 DKK (tilbageholdt af SG). Foreslået modregning: 89.000 DKK. Restbeløb: 56.000 DKK til MT. Status: SG bestrider pris på MT-2026-0404. Afventer ordrebekræftelse.", metadata: { fileName: "StaalGruppen_Afregningsforslag.docx", author: "Tina Gram", lastModified: daysAgoDate(9) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 4 — Production quality issue cascade (~15 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 14, content: "Morten, intern kvalitetsrapport: Batch 2024-Q1-447 har 12 af 50 emner uden for tolerance ±0,05mm. Borediameteren viser afvigelser op til ±0,12mm. CMM-målingerne er vedhæftet. Batchen er sat i karantæne. Vi skal have en CAPA inden den kan frigives. Lone Dahl, QA", metadata: { from: "lone@meridian-teknik.dk", to: "morten@meridian-teknik.dk", cc: "soeren.v@meridian-teknik.dk", subject: "Intern kvalitetsrapport — Batch 447 tolerance", date: daysAgoDate(14) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 12, content: "Lone, batchen er reworked og gensendt. Alle 12 emner er drejet om til specifikation. Nye målinger er inden for tolerance. Sagen er lukket. Morten", metadata: { from: "morten@meridian-teknik.dk", to: "lone@meridian-teknik.dk", subject: "RE: Batch 447 — reworked og lukket", date: daysAgoDate(12) } },

  // This week: 3 complaints arrive
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 3, content: "Til Meridian Teknik A/S. Vi har modtaget leverance fra ordre GF-2026-112 og konstateret at 8 af 30 komponenter ikke overholder specifikationen på borediameteren (±0,05mm). Vi anmoder om omgående udskiftning og en forklaring på kvalitetsafvigelsen. Peter Skou, Component Buyer, Grundfos A/S", metadata: { from: "peter.skou@grundfos.com", to: "katja@meridian-teknik.dk", cc: "lone@meridian-teknik.dk", subject: "Kvalitetsklage — Ordre GF-2026-112", direction: "received", date: daysAgoDate(3) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 2, content: "Dear Meridian Teknik, quality issue on order VES-2026-089. We have identified tolerance deviations on 5 of 20 shaft components. The bore diameter is outside the specified ±0.05mm tolerance. Please provide root cause analysis and corrective action within 48 hours. This is critical as the components are for our Horns Rev 4 project. Mette Abildgaard, Supply Chain Manager, Vestas Wind Systems", metadata: { from: "mette.abildgaard@vestas.com", to: "rene@meridian-teknik.dk", cc: "lone@meridian-teknik.dk", subject: "Quality Issue — Order VES-2026-089", direction: "received", date: daysAgoDate(2) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 2, content: "Dear Katja, we've identified tolerance deviations on the latest shipment (PO ref: PC-2026-0034). The bore diameter on 4 of 15 components exceeds the specified ±0.05mm tolerance. This is the second quality issue in 6 months and we will need to review our supply arrangement if it continues. Please advise on corrective measures. Best regards, James Wilson-Park, Purchasing Director, Precision Components Ltd", metadata: { from: "james.wilson-park@precisioncomponents.co.uk", to: "katja@meridian-teknik.dk", cc: "lone@meridian-teknik.dk", subject: "Quality concern — PO PC-2026-0034", direction: "received", date: daysAgoDate(2) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 2, content: "Morten, de tre reklamationer fra Grundfos, Vestas og Precision Components peger alle på borediameter-afvigelser. Batchnumrene er forskellige men de er alle produceret i uge 10-11 på CNC-3. Reworket af batch 447 var tilsyneladende ikke komplet — eller problemet er maskinrelateret og ikke batchspecifikt. Vi er nødt til at stoppe produktion på CNC-3 og kalibrere. Lone", metadata: { from: "lone@meridian-teknik.dk", to: "morten@meridian-teknik.dk", cc: "jorgen@meridian-teknik.dk", subject: "3 reklamationer — mulig systematisk fejl CNC-3", date: daysAgoDate(2) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 1, content: "Lone, produktion har fulgt proceduren. Reworket af batch 447 blev udført korrekt og målinger viste godkendte værdier. Hvis CNC-3 har et problem er det vedligeholdelse, ikke produktion. Vi kan ikke stoppe maskinen — vi har Danfoss-ordrer der skal ud. Morten", metadata: { from: "morten@meridian-teknik.dk", to: "lone@meridian-teknik.dk", cc: "jorgen@meridian-teknik.dk", subject: "RE: 3 reklamationer — produktion har fulgt procedure", date: daysAgoDate(1) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 1, content: "Morten og Lone — vi holder krisemøde i morgen kl 8. Tre kunder har klaget over det SAMME problem. Det er ikke vedligeholdelse vs. produktion — det er Meridian Tekniks troværdighed der er på spil. Vi stopper CNC-3, vi kalibrerer, og vi finder root cause. Punkt. Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "morten@meridian-teknik.dk", cc: "lone@meridian-teknik.dk, torben@meridian-teknik.dk, henrik.b@meridian-teknik.dk", subject: "Krisemøde i morgen kl 8 — kvalitetsproblemer", date: daysAgoDate(1) } },

  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 0, content: "KRISEMØDE: Kvalitetsproblemer CNC-3. Deltagere: Jørgen, Morten, Lone, Torben, Henrik.B. 3 kundeeskalationer (Grundfos, Vestas, Precision Components) med identisk toleranceproblem. CNC-3 stoppes for kalibrering. Henrik undersøger værktøjsslitage og maskingeometri. Handlingsplan kræves inden fredag.", metadata: { title: "KRISEMØDE: Kvalitet — CNC-3 borediameter", attendees: ["jorgen@meridian-teknik.dk", "morten@meridian-teknik.dk", "lone@meridian-teknik.dk", "torben@meridian-teknik.dk", "henrik.b@meridian-teknik.dk"], date: daysAgoDate(0) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 0, content: "Corrective Action Report — Batch 447 og relaterede leverancer. Status: UDKAST — UFULDSTÆNDIG. Problem: Borediameter-afvigelser (±0,12mm vs. spec ±0,05mm) konstateret på leverancer til Grundfos, Vestas og Precision Components. Alle produceret på CNC-3 i uge 10-11. Root cause: UNDER UNDERSØGELSE. Mulige årsager: 1) Værktøjsslitage (skær ikke udskiftet iht. plan?), 2) Maskingeometri (CNC-3 sidst kalibreret jan. 2026), 3) Programmering (reference offset?). Korrigerende handlinger: AFVENTER. Forebyggende handlinger: AFVENTER.", metadata: { fileName: "CAR_Batch447_kvalitetsproblemer_UDKAST.docx", author: "Lone Dahl", lastModified: daysAgoDate(0) } },

  // Katja connecting Müller's old complaint
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 1, content: "Lone — det her er det SAMME batch og det SAMME toleranceproblem som Müller klagede over for 2 måneder siden. Dr. Schneider sagde 12 af 50 var udenfor spec. Reworket løste åbenbart ikke det underliggende problem. Det forklarer hvorfor Müller er gået tavse. Katja", metadata: { from: "katja@meridian-teknik.dk", to: "lone@meridian-teknik.dk", cc: "jorgen@meridian-teknik.dk", subject: "FW: Müller batch 447 = SAMME problem", date: daysAgoDate(1) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 5 — Cash flow pressure (~8 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 5, content: "Jørgen, her er likviditetsoversigten for marts. Udestående fordringer over 30 dage: 1.788.000 DKK. Fordelt: FLSmidth 310K (45 dage — projektfaktura, de siger 'afventer godkendelse'), StålGruppen 145K (tilbageholdt), Novozymes 210K (de har normalt 45 dages betaling men er 18 dage over), NorthPower 78K (10 dage over). Danfoss betaler til tiden men næste store faktura (480K) er sendt for 10 dage siden. Vi har 890K i kassen. Kommende betalinger: DSV 67K (forfald om 3 dage), KUKA 340K (forfald om 10 dage), lønninger 650K (den 1.). Vi kan IKKE betale alt. Birgitte", metadata: { from: "birgitte@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "Likviditetsoversigt marts — KRITISK", date: daysAgoDate(5) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 4, content: "Birgitte, vi kan ikke betale DSV-fakturaen denne måned uden at Danfoss betaler først. Ring til Charlotte Riis og spørg om de kan fremrykke betalingen af MT-2026-0402. Og kontakt FLSmidth — 45 dage er uacceptabelt. KUKA kan vi muligvis udskyde med 14 dage hvis vi forklarer situationen. Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "birgitte@meridian-teknik.dk", subject: "RE: Likviditetsoversigt — prioritering", date: daysAgoDate(4) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 4, content: "Udestående fordringer — Aging Report, marts 2026. 0-30 dage: 670.000 DKK (Danfoss 480K, PC Ltd 145K, Nordic Tech 95K). 31-45 dage: 1.033.000 DKK (FLSmidth 310K, StålGruppen 145K, Novozymes 210K, DV 45K, NP 78K, andre 245K). Over 45 dage: 755.000 DKK (diverse småkunder). Total udestående: 2.458.000 DKK. Heraf over 30 dage: 1.788.000 DKK. Risiko: FLSmidth (projektgodkendelse), StålGruppen (modregningsdispute), Novozymes (atypisk sent).", metadata: { fileName: "Aging_Report_marts2026.xlsx", author: "Tina Gram", lastModified: daysAgoDate(4) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 3, content: "Jørgen, opdatering: Charlotte (Danfoss) kan ikke fremrykke — deres betalingscyklus er fast. FLSmidth siger godkendelsen kommer 'inden for 2 uger'. Jeg har skrevet til KUKA om 14 dages udsættelse. DSV-fakturaen MÅ vi betale — de truer med at stoppe vores forsendelser. Birgitte", metadata: { from: "birgitte@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "RE: Likviditet — opdatering", date: daysAgoDate(3) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 3, content: "Cash Flow Forecast — april 2026. Indbetalinger (forventet): Danfoss 480K (uge 15), StålGruppen 56K (modregning), PC Ltd 145K (uge 16), Nordic Tech 95K (uge 15). Total forventet: 776K. Udbetalinger: Lønninger 650K (1/4), DSV 67K (forfald), KUKA 340K (udskudt?), materialer 180K, husleje 45K. Total udbetalinger: 1.282K. UNDERSKUD: 506K. SCENARIO: Hvis Danfoss og KUKA-udsættelse: +130K. Hvis FLSmidth betaler: +440K. Status: KRITISK — kræver minimum Danfoss + 1 anden betaling.", metadata: { fileName: "CashFlow_Forecast_april2026.xlsx", author: "Birgitte Holm", lastModified: daysAgoDate(3) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 6 — ISO 9001 audit (~8 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 25, content: "Kære afdelingsledere, vores ISO 9001 surveillance audit er planlagt om 5 uger (uge 18). Vi har aktuelt 4 åbne afvigelser fra seneste interne audit: NC-2026-001: Kalibreringscertifikat for CMM udløbet (ansvarlig: Henrik.B). NC-2026-002: Manglende sporbarhed på batch 398 (ansvarlig: Kim). NC-2026-003: CAPA for kundeeskalation batch 447 ikke udfyldt (ansvarlig: Morten). NC-2026-004: Forældet arbejdsinstruks for CNC-3 (ansvarlig: Morten). Alle afvigelser SKAL være lukket inden audit. Venligst bekræft status inden fredag. Lone Dahl, QA Manager", metadata: { from: "lone@meridian-teknik.dk", to: "morten@meridian-teknik.dk", cc: "henrik.b@meridian-teknik.dk, kim@meridian-teknik.dk, jorgen@meridian-teknik.dk", subject: "ISO 9001 audit om 5 uger — 4 åbne afvigelser", date: daysAgoDate(25) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 14, content: "Morten, jeg mangler stadig din CAPA for NC-2026-003 (batch 447) og opdateret arbejdsinstruks for CNC-3 (NC-2026-004). Det er 11 dage siden min første mail. Bureau Veritas-auditoren kommer om 3 uger. Hvis vi har åbne major non-conformances risikerer vi en opfølgningsaudit til 45.000 DKK. Venligst prioritér dette. Lone", metadata: { from: "lone@meridian-teknik.dk", to: "morten@meridian-teknik.dk", subject: "RYKKER: CAPA NC-2026-003 og NC-2026-004", date: daysAgoDate(14) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 7, content: "Jørgen, Morten har ikke svaret på mine 2 henvendelser om CAPA for batch 447 og CNC-3 arbejdsinstruks. Det er nu 18 dage. Auditen er om 3 uger. Henrik har lukket NC-2026-001 (kalibrering), Kim har lukket NC-2026-002 (sporbarhed). Men Mortens 2 afvigelser er kritiske. Lone", metadata: { from: "lone@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "Eskalering: Morten — 2 åbne NC'er til ISO audit", date: daysAgoDate(7) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 20, content: "Intern Audit Report Q1 2026 — Meridian Teknik A/S. Auditor: Lone Dahl. Scope: ISO 9001:2015, alle afdelinger. Findings: NC-2026-001 (Minor): CMM kalibreringscertifikat udløbet 15. feb. NC-2026-002 (Minor): Batch 398 mangler materialecertifikat i sporbarhesmappe. NC-2026-003 (Major): Kundeeskalation vedr. batch 447 — CAPA ikke udfyldt trods proceduren kræver det inden 10 hverdage. NC-2026-004 (Minor): Arbejdsinstruks AI-CNC-003 sidst revideret 2023 — skal opdateres. Samlet vurdering: 2 minor og 2 major NC'er. Kræver handling inden ekstern audit uge 18.", metadata: { fileName: "Intern_Audit_Q1_2026.docx", author: "Lone Dahl", lastModified: daysAgoDate(20) } },

  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 25, content: "ISO 9001 surveillance audit — Bureau Veritas. Auditor: Philippe Moreau. Varighed: 2 dage. Scope: Produktion, QA, Logistik, Engineering. Forberedelse: Alle NC'er skal være lukket. Dokumentation skal være opdateret.", metadata: { title: "ISO 9001 Surveillance Audit — Bureau Veritas", attendees: ["lone@meridian-teknik.dk", "jorgen@meridian-teknik.dk", "morten@meridian-teknik.dk"], date: daysAgoDate(-10) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 7 — Vestas framework opportunity (~6 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 14, content: "Til Meridian Teknik A/S, att. Jørgen Lund. Vestas Wind Systems A/S inviterer hermed Meridian Teknik til at afgive tilbud på en 3-årig rammeaftale for levering af præcisionsdrejede og fræsede komponenter til vores vindmølle-naceller. Estimeret årlig volumen: 8.000.000 DKK. Krav: ISO 9001 (obligatorisk), ISO 14001 (stærkt foretrukket), CE-mærkning, 100% sporbarhed. Tilbudsfrist: 30. april 2026. Detaljeret RFP vedhæftet. Lars Bonde, Procurement Director, Vestas Wind Systems A/S", metadata: { from: "lars.bonde@vestas.com", to: "jorgen@meridian-teknik.dk", subject: "RFP: 3-årig rammeaftale for præcisionskomponenter — Vestas", direction: "received", date: daysAgoDate(14) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 13, content: "Alle — vi har modtaget en RFP fra Vestas på en 3-årig rammeaftale. 8M DKK årligt. Dette ville ændre vores forretning fundamentalt. Problemet: De kræver ISO 14001 som vi ikke har. Birgitte — hvad koster certificeringen? Henrik — kan vi producere nacelle-komponenterne? Torben — sæt René på det. Vi mødes i morgen. Jørgen", metadata: { from: "jorgen@meridian-teknik.dk", to: "birgitte@meridian-teknik.dk", cc: "torben@meridian-teknik.dk, henrik.b@meridian-teknik.dk, morten@meridian-teknik.dk", subject: "Vestas RFP — 8M DKK/år — PRIORITET", date: daysAgoDate(13) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 11, content: "Jørgen, ISO 14001-certificering: Estimerede omkostninger 200-400K DKK afhængig af scope. Tidshorisont: 6-9 måneder fra beslutning. Vi kan kontakte Bureau Veritas for et indledende møde. Vi har IKKE budget til det i 2026-planen — det kræver ekstra investering. Birgitte", metadata: { from: "birgitte@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "RE: Vestas — ISO 14001 omkostninger", date: daysAgoDate(11) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 10, content: "Jørgen, teknisk vurdering: Vi kan producere nacelle-komponenterne men det kræver: 1) Ny Ø400mm 4-akset drejebænk (estimat 1,2M DKK), 2) Udvidet CMM-kapacitet, 3) Minimum 2 ekstra CNC-operatører. Henrik.B", metadata: { from: "henrik.b@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "RE: Vestas — teknisk kapacitetsvurdering", date: daysAgoDate(10) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 8, content: "Vestas Framework Bid — Feasibility Assessment. RFP: 3-årig rammeaftale, 8M DKK/år. Teknisk: MULIGT med investering (ny drejebænk Ø400, CMM-udvidelse, 2 operatører). Certificering: ISO 14001 nødvendig (6-9 mdr, 200-400K DKK). Kapacitet: Kræver 15-20% ekstra kapacitet — vi kører 94% nu. Investering total: ~1,8M DKK (maskine + certificering + rekruttering). ROI: Payback på 8-10 måneder ved fuld volumen. Risici: Eksisterende kvalitetsproblemer (batch 447) kan diskvalificere os. ISO 9001 audit resultat er kritisk. Anbefaling: BYD — men luk kvalitetsproblemerne FØRST.", metadata: { fileName: "Vestas_Framework_Feasibility.docx", author: "Torben Krogh", lastModified: daysAgoDate(8) } },

  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 6, content: "Vestas strategi-møde. Jørgen, Birgitte, Torben, Henrik.B, Morten. Gennemgang af feasibility-vurdering. Beslutning: Vi byder — men med forbehold for ISO 14001 tidsplan. René udarbejder tilbuddet. Henrik laver tekniske specifikationer. Birgitte kontakter Bureau Veritas om ISO 14001 pre-assessment. FORUDSÆTNING: Kvalitetsproblemerne med CNC-3 SKAL være løst inden tilbudsafgivelse.", metadata: { title: "Vestas rammeaftale — strategimøde", attendees: ["jorgen@meridian-teknik.dk", "birgitte@meridian-teknik.dk", "torben@meridian-teknik.dk", "henrik.b@meridian-teknik.dk", "morten@meridian-teknik.dk"], date: daysAgoDate(6) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 8 — Hannover Messe leads going cold (~6 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 21, content: "Torben, Hannover Messe var en succes! Vi havde 25 konkrete leads ved standen — en blanding af Nordeuropa og Benelux. Bedste leads: Alfa Laval (Sverige, stor potentiale), et belgisk maskinbyggeri, og 3 tyske virksomheder der kender Müller (omvendt er det godt — vi viser at vi er på markedet). Jeg sender listen til HubSpot i morgen. Andreas", metadata: { from: "andreas@meridian-teknik.dk", to: "torben@meridian-teknik.dk", subject: "Hannover Messe — 25 leads! 🎉", date: daysAgoDate(21) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 20, content: "Godt arbejde Andreas! Sørg for at alle 25 leads kommer i HubSpot med kontaktinfo, virksomhed, produktinteresse og temperatur (hot/warm/cold). Ditte kan hjælpe med opfølgning. Vi skal have dem ringet op inden de glemmer os. Torben", metadata: { from: "torben@meridian-teknik.dk", to: "andreas@meridian-teknik.dk", subject: "RE: Hannover Messe — HubSpot ASAP", date: daysAgoDate(20) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 7, content: "Andreas, jeg kan kun finde 5 af Hannover-leadene i HubSpot. Hvor er de andre 20? Gustav Nilsson fra Alfa Laval er den eneste af de 'hot' leads der er registreret. Ditte", metadata: { from: "ditte@meridian-teknik.dk", to: "andreas@meridian-teknik.dk", subject: "Hannover leads — kun 5 i HubSpot?", date: daysAgoDate(7) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 6, content: "Ditte, beklager — jeg har resten i et Excel-regneark. Har haft travlt med Alfa Laval-opfølgningen. Uploader de resterende i denne uge. Andreas", metadata: { from: "andreas@meridian-teknik.dk", to: "ditte@meridian-teknik.dk", subject: "RE: Hannover leads — uploader snart", date: daysAgoDate(6) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 21, content: "Hannover Messe 2026 — Lead List. Dato: marts 2026. Standnr: Hall 5, B42. Total besøgende: ~80. Kvalificerede leads: 25. HOT (kontaktes inden 1 uge): 1) Alfa Laval AB — Gustav Nilsson, Supplier Development. 2) Bosch Rexroth AG — Thomas Keller, Procurement. 3) ThyssenKrupp Rothe Erde — Andreas Müller, Technical Buyer. WARM (kontaktes inden 2 uger): 4-12 [diverse virksomheder]. COLD (nyhedsbrev): 13-25 [diverse]. BEMÆRK: Kun overført til HubSpot: #1 (Alfa Laval). Status: 20 leads IKKE i CRM.", metadata: { fileName: "Hannover_Messe_2026_Leads.xlsx", author: "Andreas Pihl", lastModified: daysAgoDate(21) } },

  { sourceType: "slack_message", connectorProvider: "microsoft-365-teams", daysAgo: 5, content: "Torben — det er 3 uger siden Hannover og vi har stadig kun 5 leads i HubSpot. De hot leads er ved at blive kolde. Kan vi please få Andreas til at prioritere det?", metadata: { channel: "salg", authorEmail: "ditte@meridian-teknik.dk", authorName: "Ditte Laursen" } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 9 — Henrik.B knowledge silo (~6 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 8, content: "Henrik, kan du konvertere denne CAD-fil til CNC-format? Kunden har sendt i STEP og vores postprocessor giver fejl. Jeg ved ikke hvordan man konfigurerer offsets for den type geometri. Julie", metadata: { from: "julie@meridian-teknik.dk", to: "henrik.b@meridian-teknik.dk", subject: "CAD til CNC konvertering — STEP fil", date: daysAgoDate(8) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 6, content: "Henrik, CNC-3 programmet kørte fejl igen i dag — vi fik en crash midt i cyklus. Per og jeg prøvede at rette det men vi forstår ikke opsætningen af værktøjsskift-sekvensen. Kun du forstår den konfiguration. Kan du kigge på det? Lasse", metadata: { from: "lasse@meridian-teknik.dk", to: "henrik.b@meridian-teknik.dk", subject: "CNC-3 program fejl — crash i cyklus", date: daysAgoDate(6) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 4, content: "Lasse, kan du se om Henrik har svaret på CNC-3-problemet? Jeg har også brug for ham til Danfoss-specifikationen. Han er den eneste der kan lave hydraulik-beregningerne. Julie", metadata: { from: "julie@meridian-teknik.dk", to: "lasse@meridian-teknik.dk", subject: "Henrik — har han svaret?", date: daysAgoDate(4) } },

  // Henrik was sick — production stalled
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 10, content: "Alle i produktion og engineering — Henrik er syg i dag og i morgen. Vi kan desværre ikke køre CNC-3 jobbene der kræver program-justeringer. Per og Niels kører de standard-jobs der allerede er programmeret. Eventuelle hasteordrer der kræver ny programmering må vente til Henrik er tilbage. Morten", metadata: { from: "morten@meridian-teknik.dk", to: "hanne@meridian-teknik.dk", cc: "per@meridian-teknik.dk, niels@meridian-teknik.dk, lasse@meridian-teknik.dk, julie@meridian-teknik.dk", subject: "Henrik syg — CNC-3 programmer på hold", date: daysAgoDate(10) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 9, content: "Jørgen, vi er for afhængige af Henrik. Da han var syg i 2 dage stod CNC-3 stille og vi mistede produktion for ca. 80.000 DKK. Hverken Per, Lasse eller Julie kan køre de komplekse programmer. Hvis Henrik stopper — eller bare er syg i en uge — er vi i alvorlige problemer. Vi skal have dokumenteret hans viden og trænet mindst én person mere. Morten", metadata: { from: "morten@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "Henrik Bjerregaard — single point of failure", date: daysAgoDate(9) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 730, content: "CNC-3 Setup Guide — Henrik Bjerregaard. Version 1.0. Dato: marts 2024. Indhold: 1) Maskinparametre og offsets. 2) Værktøjsbibliotek. 3) Postprocessor-konfiguration. 4) Fejlkoder og troubleshooting. BEMÆRK: Denne guide er baseret på den originale maskinopsætning. Efterfølgende ændringer (firmware-opdatering sept. 2024, ny spindel feb. 2025, tilføjelse af 4. akse juni 2025) er IKKE dokumenteret.", metadata: { fileName: "CNC3_Setup_Guide_v1.0.docx", author: "Henrik Bjerregaard", lastModified: daysAgoDate(730) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 10 — Hanne planning bottleneck (~5 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 3, content: "Hanne, jeg har brug for produktionsplanen for næste uge — Danfoss-kunden spørger om leveringstid på ordre DF-2026-118 og jeg kan ikke svare før planen er klar. Kim", metadata: { from: "kim@meridian-teknik.dk", to: "hanne@meridian-teknik.dk", subject: "Produktionsplan uge 14 — leveringstid?", date: daysAgoDate(3) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 2, content: "Hanne, planen for mandag mangler stadig. CNC-1 og CNC-2 operatørerne ved ikke hvad de skal køre. Kan du give os i det mindste en foreløbig plan? Niels", metadata: { from: "niels@meridian-teknik.dk", to: "hanne@meridian-teknik.dk", subject: "Produktionsplan mandag — HASTER", date: daysAgoDate(2) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 2, content: "Morten, jeg kan ikke nå det hele. Jeg har 15 ordrer der skal planlægges, 3 ændringer fra salg (Torben ændrede prioritet på Grundfos i går), og Henrik har ændret køretider på 4 jobs efter CNC-3 omprogrammering. Jeg er alene om produktionsplanlægningen for en fabrik med 10 maskiner og 10 operatører. Hanne", metadata: { from: "hanne@meridian-teknik.dk", to: "morten@meridian-teknik.dk", subject: "Produktionsplanlægning — overbelastet", date: daysAgoDate(2) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 1, content: "Hanne, jeg forstår godt frustrationen. Vi finder en løsning — måske kan Palle hjælpe med at automatisere noget af planlægningen i ERP'et. Lad os snakke om det på produktionsmødet i morgen. Morten", metadata: { from: "morten@meridian-teknik.dk", to: "hanne@meridian-teknik.dk", subject: "RE: Produktionsplanlægning — vi finder en løsning", date: daysAgoDate(1) } },

  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 0, content: "Produktionsmøde. Morten, Hanne, Niels, Per. Hovedpunkt: Hannes overbelastning. 15 ordrer i kø, 3 ændringer fra salg, Henrik ændrer køretider. Hanne er alene. Forslag: Palle automatiserer dele af planlægningen (men han er kun tirsdag/torsdag). Midlertidig løsning: Niels hjælper med at prioritere ordrekøen.", metadata: { title: "Produktionsmøde — planlægning", attendees: ["morten@meridian-teknik.dk", "hanne@meridian-teknik.dk", "niels@meridian-teknik.dk", "per@meridian-teknik.dk"], date: daysAgoDate(0) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 11 — Annual reviews overdue (~5 items)
  // ═══════════════════════════════════════════════════════════════════════

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 21, content: "Kære afdelingsledere, dette er en påmindelse om at de årlige medarbejdersamtaler skal være afholdt inden 15. marts. Venligst book samtaler med alle jeres medarbejdere og indsend skemaerne til mig. Skabelon er vedhæftet. Anne-Marie Olsen, HR", metadata: { from: "annemarie@meridian-teknik.dk", to: "morten@meridian-teknik.dk", cc: "torben@meridian-teknik.dk, lone@meridian-teknik.dk, kim@meridian-teknik.dk, birgitte@meridian-teknik.dk, jorgen@meridian-teknik.dk", subject: "Påmindelse: Årlige medarbejdersamtaler — frist 15. marts", date: daysAgoDate(21) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 7, content: "Kære ledere, status på medarbejdersamtaler: Gennemført: 8 af 35 (23%). Torben: 5/7. Lone: 2/3. Birgitte: 1/4. Morten: 0/10. Kim: 0/4. Fristen var 15. marts — vi er 2 uger bagud. Morten: du har 10 medarbejdere og INGEN samtaler er afholdt. Venligst prioriter dette omgående. Anne-Marie", metadata: { from: "annemarie@meridian-teknik.dk", to: "morten@meridian-teknik.dk", cc: "jorgen@meridian-teknik.dk, birgitte@meridian-teknik.dk, torben@meridian-teknik.dk, lone@meridian-teknik.dk, kim@meridian-teknik.dk", subject: "RYKKER: Medarbejdersamtaler — 8 af 35 gennemført", date: daysAgoDate(7) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 5, content: "Jørgen, Morten har igen underprioriteret HR-opgaverne. 0 af 10 samtaler gennemført og fristen var for 2 uger siden. Det er ikke kun en formalitet — vi har medarbejdere der har bedt om udviklingssamtaler og løndiskussioner. Birgitte", metadata: { from: "birgitte@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "Morten — medarbejdersamtaler (0/10)", date: daysAgoDate(5) } },

  { sourceType: "drive_doc", connectorProvider: "microsoft-365-onedrive", daysAgo: 60, content: "Medarbejdersamtale — Skabelon 2026. Medarbejder: [Navn]. Stilling: [Stilling]. Leder: [Leders navn]. Dato: [Dato]. Punkter: 1) Status på mål fra sidste år. 2) Nye mål for 2026. 3) Kompetenceudvikling og ønsker. 4) Trivsel og arbejdsmiljø. 5) Lønforventninger (kun til HR-brug). Underskrift medarbejder: ___. Underskrift leder: ___.", metadata: { fileName: "Medarbejdersamtale_Skabelon_2026.docx", author: "Anne-Marie Olsen", lastModified: daysAgoDate(60) } },

  // ═══════════════════════════════════════════════════════════════════════
  // Thread 12 — General org signals (~20 items)
  // ═══════════════════════════════════════════════════════════════════════

  // Leadership weekly #1
  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 0, content: "Ledelsesmøde. Jørgen, Birgitte, Torben, Morten. Punkter: 1) Kvalitetskrise CNC-3 — 3 kunder, krisemøde i morgen. 2) Likviditet — 1,8M over 30 dage, DSV skal betales. 3) Vestas-bid — beslutning om at byde. 4) Müller — Jørgen ringer Schneider. 5) Medarbejdersamtaler — Morten: 0/10.", metadata: { title: "Ugentligt ledelsesmøde", attendees: ["jorgen@meridian-teknik.dk", "birgitte@meridian-teknik.dk", "torben@meridian-teknik.dk", "morten@meridian-teknik.dk"], recurring: true, date: daysAgoDate(0) } },

  // Leadership weekly #2
  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 7, content: "Ledelsesmøde. Jørgen, Birgitte, Torben, Morten. Punkter: 1) Danfoss-fornyelse — Henrik mangler kapacitet. 2) StålGruppen — modregningsforslag sendt. 3) ISO audit forberedelse — 4 åbne NC'er. 4) Hannover leads — Andreas skal uploade til HubSpot. 5) Cash flow stabil men stramt.", metadata: { title: "Ugentligt ledelsesmøde", attendees: ["jorgen@meridian-teknik.dk", "birgitte@meridian-teknik.dk", "torben@meridian-teknik.dk", "morten@meridian-teknik.dk"], recurring: true, date: daysAgoDate(7) } },

  // Leadership weekly #3
  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 14, content: "Ledelsesmøde. Jørgen, Birgitte, Torben, Morten. Punkter: 1) Batch 447 rework afsluttet (Morten: 'sagen er lukket'). 2) Vestas RFP modtaget — fantastisk mulighed. 3) Hannover Messe — Andreas: 25 leads. 4) Müller stadig tavse. 5) Budget Q2 gennemgang.", metadata: { title: "Ugentligt ledelsesmøde", attendees: ["jorgen@meridian-teknik.dk", "birgitte@meridian-teknik.dk", "torben@meridian-teknik.dk", "morten@meridian-teknik.dk"], recurring: true, date: daysAgoDate(14) } },

  // Sales standup
  { sourceType: "calendar_note", connectorProvider: "microsoft-365-calendar", daysAgo: 2, content: "Salgsmøde. Torben, Christian, Katja, René, Ditte, Mikael, Andreas. Pipeline: Danfoss fornyelse (René), Vestas RFP (Jørgen/René), Alfa Laval lead (Andreas). Problemer: Müller tavse (Katja), Hannover leads ikke i CRM (Andreas/Ditte). Action: Andreas uploader leads DENNE UGE.", metadata: { title: "Ugentligt salgsmøde", attendees: ["torben@meridian-teknik.dk", "christian@meridian-teknik.dk", "katja@meridian-teknik.dk", "rene@meridian-teknik.dk", "ditte@meridian-teknik.dk", "mikael@meridian-teknik.dk", "andreas@meridian-teknik.dk"], recurring: true, date: daysAgoDate(2) } },

  // Production daily Teams
  { sourceType: "slack_message", connectorProvider: "microsoft-365-teams", daysAgo: 1, content: "Produktion dag-status: CNC-1 kører Grundfos-ordren (Niels). CNC-2 kører Danfoss standard (Per + Lars). CNC-3 STOPPET for kalibrering efter kvalitetsproblem. Fræser-1 kører Dansk Ventilation (Thomas.A). Kapacitet: 82% (pga. CNC-3 stop). Morten", metadata: { channel: "produktion", authorEmail: "morten@meridian-teknik.dk", authorName: "Morten Bak" } },

  { sourceType: "slack_message", connectorProvider: "microsoft-365-teams", daysAgo: 3, content: "Produktion dag-status: CNC-1 Grundfos (Niels). CNC-2 Danfoss (Per). CNC-3 batch 447 opfølgning + NorthPower (Henrik prog.). Fræser-1 vedligehold. Kapacitet: 94%. Vi er presset — Hanne: planen for næste uge? Morten", metadata: { channel: "produktion", authorEmail: "morten@meridian-teknik.dk", authorName: "Morten Bak" } },

  // Logistics coordination
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 4, content: "Thomas.J, forsendelsen til Precision Components (PC-2026-0034) skal afsted med DSV i morgen. 15 dele, total vægt 48 kg. Sørg for korrekt CE-mærkning og materialecertifikater i forsendelsen. Kim", metadata: { from: "kim@meridian-teknik.dk", to: "thomas.j@meridian-teknik.dk", subject: "Forsendelse Precision Components — i morgen", date: daysAgoDate(4) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 3, content: "Kim, DSV har meddelt ny prisstruktur fra 1. april. Fragt til UK stiger 8%. Det påvirker alle Precision Components-forsendelser. Bo beregner impact på vores leveringsomkostninger. Thomas.J", metadata: { from: "thomas.j@meridian-teknik.dk", to: "kim@meridian-teknik.dk", subject: "DSV — nye fragtrater fra 1. april", date: daysAgoDate(3) } },

  // QA weekly
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 1, content: "QA Ugerapport uge 13. Inspicerede batcher: 12. Godkendte: 10. Afvist: 2 (begge CNC-3, bore-diameter). Kundeeskalationer: 3 (Grundfos, Vestas, PC Ltd — alle CNC-3 relateret). Åbne NC'er: 4 (2 af Mortens udestående). ISO-audit status: 3 uger til ekstern audit, 2 major NC'er åbne. Lone Dahl, QA Manager", metadata: { from: "lone@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", cc: "morten@meridian-teknik.dk", subject: "QA Ugerapport uge 13", date: daysAgoDate(1) } },

  // Finance monthly
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 5, content: "Jørgen, månedlig finansiel opsummering februar 2026. Omsætning: 3,2M DKK (budget: 3,5M — 91%). Direkte omkostninger: 2,1M DKK. Driftsresultat: 380K DKK (budget: 520K). Likviditet: 890K DKK. Udestående over 30 dage: 1,8M DKK. Personaleomkostninger: 1,15M DKK (inkl. Claus provision 18K). BEMÆRK: Claus' provision er bogført under personaleomkostninger men han er ikke på lønningslisten. Birgitte", metadata: { from: "birgitte@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", subject: "Månedlig opsummering februar 2026", date: daysAgoDate(5) } },

  // Claus: commission invoice from Sweden
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 8, content: "Hej Birgitte, vedhæftet er min provisionsfaktura for februar. Total: 18.400 DKK (7% af Nordic Tech Solutions-ordren på 263K DKK). Bankoplysninger som sædvanlig. Jeg er i Göteborg resten af ugen — ring hvis der er spørgsmål. Vh Claus Lundberg", metadata: { from: "claus@meridian-teknik.dk", to: "birgitte@meridian-teknik.dk", subject: "Provisionsfaktura februar 2026", date: daysAgoDate(8) } },

  // Susanne: office management
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 6, content: "Alle — printeren på 1. sal er i stykker igen. Serviceteknikeren kommer torsdag. Brug printeren i produktionshallen indtil da. Og husk: parkeringspladsen foran hovedindgangen er IKKE til personale — den er til kunder og besøgende. Susanne", metadata: { from: "susanne@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", cc: "birgitte@meridian-teknik.dk", subject: "Printer 1. sal + parkering", date: daysAgoDate(6) } },

  // Palle: IT / ERP
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 10, content: "Alle — planlagt nedetid på ERP-systemet søndag kl 22-02 for databasevedligeholdelse. Produktionsplanlægning, ordreregistrering og e-conomic-integration vil være utilgængelig. Palle Svendsen, IT", metadata: { from: "palle@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", cc: "birgitte@meridian-teknik.dk, hanne@meridian-teknik.dk, tina@meridian-teknik.dk", subject: "Planlagt ERP-nedetid søndag aften", date: daysAgoDate(10) } },

  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 4, content: "Hanne, den automatiserede ordreimport fra e-conomic til ERP'et kan desværre ikke laves før maj. Jeg er her tirsdag og torsdag og har 3 andre projekter foran. Integrationen kræver en ny API-connector og test. Kan det vente? Palle", metadata: { from: "palle@meridian-teknik.dk", to: "hanne@meridian-teknik.dk", subject: "ERP-automatisering — tidligst maj", date: daysAgoDate(4) } },

  // Teams #kantine
  { sourceType: "slack_message", connectorProvider: "microsoft-365-teams", daysAgo: 3, content: "Påskefrokost fredag den 11. april kl 11:30. Susanne bestiller fra Meyers. Tilmeld jer inden onsdag. Pris: 75 DKK/person (firma betaler halvdelen). 🐣", metadata: { channel: "kantine", authorEmail: "susanne@meridian-teknik.dk", authorName: "Susanne Berg" } },

  // Holiday planning
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 15, content: "Kære alle, husk at indsende jeres ferieanmodning for sommerferie (uge 27-31) inden 1. april. Produktion holder lukket uge 29-30, men vi skal have bemanding i logistik uge 29 pga. Danfoss-leverancer. Koordinér med jeres afdelingsleder. Anne-Marie", metadata: { from: "annemarie@meridian-teknik.dk", to: "jorgen@meridian-teknik.dk", cc: "morten@meridian-teknik.dk, torben@meridian-teknik.dk, lone@meridian-teknik.dk, kim@meridian-teknik.dk, birgitte@meridian-teknik.dk", subject: "Sommerferie 2026 — frist 1. april", date: daysAgoDate(15) } },

  // Safety notice (production workers CC'd)
  { sourceType: "email", connectorProvider: "microsoft-365-outlook", daysAgo: 12, content: "Til alle i produktion — den årlige sikkerhedsgennemgang med Arbejdstilsynet er planlagt til 3. april. Sørg for at alle sikkerhedsskærme er monteret, øjenbryn er tilgængelige ved alle maskiner, og at komprimeret luft-pistolerne har trykreduktion under 2,5 bar. Morten", metadata: { from: "morten@meridian-teknik.dk", to: "hanne@meridian-teknik.dk", cc: "niels@meridian-teknik.dk, per@meridian-teknik.dk, lars.h@meridian-teknik.dk, thomas.a@meridian-teknik.dk, erik.m@meridian-teknik.dk, brian@meridian-teknik.dk, dennis@meridian-teknik.dk, kenneth@meridian-teknik.dk, jesper.m@meridian-teknik.dk", subject: "Arbejdstilsynet 3. april — sikkerhedsforberedelse", date: daysAgoDate(12) } },
];
